[package]
name = "s3du"
version = "0.1.0"
authors = ["David O'Rourke <david.orourke@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"

[features]
# Build with both CloudWatch and S3 support by default
default = ["cloudwatch", "s3"]

# Only CloudWatch support
cloudwatch = ["rusoto_cloudwatch"]

# Only S3 support
s3 = ["rusoto_s3"]

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
chrono = "0.4"
clap = "2.33"
humansize = "1.1"
log = "0.4"
pretty_env_logger = "0.4"
tokio = "0.2"

[dependencies.rusoto_cloudwatch]
version = "0.43.0"
default-features = false
features = ["rustls"]
optional = true

[dependencies.rusoto_core]
version = "0.43.0"
default-features = false
features = ["rustls"]

[dependencies.rusoto_s3]
version = "0.43.0"
default-features = false
features = ["rustls"]
optional = true

[dev-dependencies]
pretty_assertions = "0.6"

[dev-dependencies.rusoto_mock]
version = "0.43.0"
default-features = false
features = ["rustls"]
