[package]
name = "s3du"
description = "Command line utility for showing space used in AWS S3 buckets"
version = "1.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/phyber/s3du"
repository = "https://github.com/phyber/s3du"
rust-version = "1.65.0"
resolver = "2"
authors = [
    "David O'Rourke <david.orourke@gmail.com>",
]
categories = [
    "command-line-utilities",
    "filesystem",
]
keywords = [
    "aws",
    "cli",
    "s3",
]
exclude = [
    ".gitignore",
    ".github",
]

[features]
# Build with both CloudWatch and S3 support by default
default = [
    "cloudwatch",
    "s3",
]

# Only CloudWatch support
cloudwatch = [
    "aws-sdk-cloudwatch",
    "aws-smithy-types-convert",
    "chrono",
]

# Only S3 support
s3 = [
    "aws-sdk-s3",
    "aws-smithy-http",
    "http",
]

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
aws-config = "0.55.0"
aws-credential-types = "0.55.0"
aws-types = "0.55.0"
humansize = "2.1.3"
once_cell = "1.17.1"
rayon = "1.7"
tracing = "0.1"
tracing-subscriber = "0.3"

[dependencies.aws-sdk-cloudwatch]
version = "0.28.0"
optional = true

[dependencies.aws-sdk-s3]
version = "0.28.0"
optional = true

[dependencies.aws-smithy-client]
version = "0.55.0"
features = [
    "client-hyper",
    "rustls",
    "rt-tokio",
]

[dependencies.aws-smithy-http]
version = "0.55.0"
optional = true
features = [
    "rt-tokio",
]

[dependencies.aws-smithy-types-convert]
version = "0.55.0"
optional = true
features = [
    "convert-chrono",
]

[dependencies.chrono]
version = "0.4"
default-features = false
optional = true
features = [
    "clock",
    "std",
]

[dependencies.clap]
version = "4.2.1"
default-features = false
features = [
    "cargo",
    "color",
    "deprecated",
    "env",
    "error-context",
    "help",
    "std",
    "suggestions",
    "usage",
    "wrap_help",
]

[dependencies.http]
version = "0.2"
optional = true

[dependencies.tokio]
version = "1.27"
features = [
    "macros",
    "rt-multi-thread",
]

[dev-dependencies]
http = "0.2"
pretty_assertions = "1.3"

[dev-dependencies.aws-smithy-client]
version = "0.55.0"
features = [
    "test-util",
]

[dev-dependencies.aws-smithy-http]
version = "0.55.0"
features = [
    "rt-tokio",
]

# Hardcoded credentials are only used in tests.
[dev-dependencies.aws-credential-types]
version = "0.55.0"
features = [
    "hardcoded-credentials",
]
