[package]
name = "s3du"
description = "Command line utility for showing space used in AWS S3 buckets"
version = "1.1.0"
authors = ["David O'Rourke <david.orourke@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/phyber/s3du"
repository = "https://github.com/phyber/s3du"
categories = [
    "command-line-utilities",
    "filesystem",
]
keywords = [
    "aws",
    "cli",
    "s3",
]
exclude = [
    ".gitignore",
    ".github",
]

[features]
# Build with both CloudWatch and S3 support by default
default = ["cloudwatch", "s3"]

# Only CloudWatch support
cloudwatch = ["aws-sdk-cloudwatch", "chrono"]

# Only S3 support
s3 = ["aws-sdk-s3", "url"]

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
humansize = "1.1"
lazy_static = "1.4"
log = "0.4"
pretty_env_logger = "0.4"
rayon = "1.5"
tokio = "1.0"

[dependencies.aws-hyper]
git = "https://github.com/awslabs/aws-sdk-rust"
tag = "v0.0.14-alpha"

[dependencies.aws-sdk-cloudwatch]
git = "https://github.com/awslabs/aws-sdk-rust"
tag = "v0.0.14-alpha"
optional = true

[dependencies.aws-sdk-s3]
git = "https://github.com/awslabs/aws-sdk-rust"
tag = "v0.0.14-alpha"
optional = true

[dependencies.aws-types]
git = "https://github.com/awslabs/aws-sdk-rust"
tag = "v0.0.14-alpha"

[dependencies.chrono]
version = "0.4"
optional = true

[dependencies.clap]
version = "2.33"
default-features = false
features = ["color", "suggestions"]

[dependencies.smithy-client]
git = "https://github.com/awslabs/aws-sdk-rust"
tag = "v0.0.14-alpha"

[dependencies.url]
version = "2.1"
optional = true

[dev-dependencies]
http = "0.2"
pretty_assertions = "0.7"

[dev-dependencies.aws-hyper]
git = "https://github.com/awslabs/aws-sdk-rust"
tag = "v0.0.14-alpha"

[dev-dependencies.rusoto_cloudwatch]
version = "0.47.0"
default-features = false
features = ["rustls"]

[dev-dependencies.rusoto_mock]
version = "0.47.0"
default-features = false
features = ["rustls"]

[dev-dependencies.smithy-client]
git = "https://github.com/awslabs/aws-sdk-rust"
tag = "v0.0.14-alpha"
features = ["test-util"]

[dev-dependencies.smithy-http]
git = "https://github.com/awslabs/aws-sdk-rust"
tag = "v0.0.14-alpha"
