[package]
name = "s3du"
description = "Command line utility for showing space used in AWS S3 buckets"
version = "1.2.0"
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/phyber/s3du"
repository = "https://github.com/phyber/s3du"
authors = [
    "David O'Rourke <david.orourke@gmail.com>",
]
categories = [
    "command-line-utilities",
    "filesystem",
]
keywords = [
    "aws",
    "cli",
    "s3",
]
exclude = [
    ".gitignore",
    ".github",
]

[features]
# Build with both CloudWatch and S3 support by default
default = [
    "cloudwatch",
    "s3",
]

# Only CloudWatch support
cloudwatch = [
    "aws-sdk-cloudwatch",
    "aws-smithy-types-convert",
    "chrono",
]

# Only S3 support
s3 = [
    "aws-sdk-s3",
    "url",
]

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
aws-config = "0.7.0"
humansize = "1.1"
lazy_static = "1.4"
log = "0.4"
pretty_env_logger = "0.4"
rayon = "1.5"

[dependencies.aws-sdk-cloudwatch]
version = "0.7.0"
optional = true

[dependencies.aws-sdk-s3]
version = "0.7.0"
optional = true

[dependencies.aws-smithy-client]
version = "0.37.0"
features = [
    "client-hyper",
    "rustls",
    "rt-tokio",
]

[dependencies.aws-smithy-types-convert]
version = "0.37.0"
optional = true
features = [
    "convert-chrono",
]

[dependencies.aws-types]
version = "0.7.0"

[dependencies.chrono]
version = "0.4"
optional = true

[dependencies.clap]
version = "3.1.0"
default-features = false
features = [
    "cargo",
    "color",
    "env",
    "std",
    "suggestions",
]

[dependencies.tokio]
version = "1.0"
features = [
    "macros",
    "rt-multi-thread",
]

[dependencies.url]
version = "2.1"
optional = true

[dev-dependencies]
http = "0.2"
pretty_assertions = "1.0"

[dev-dependencies.aws-smithy-client]
version = "0.37.0"
features = [
    "test-util",
]

[dev-dependencies.aws-smithy-http]
version = "0.37.0"
features = [
    "rt-tokio",
]

# Hardcoded credentials are only used in tests.
[dev-dependencies.aws-types]
version = "0.7.0"
features = [
    "hardcoded-credentials",
]
