---
name: 'Continuous Integration'
on:
  push:
    branches:
      - 'main'
jobs:
  test:
    name: 'Test Suite'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        # Test against current stable and the MSRV
        toolchain-version:
          - 'stable'
          - '1.74.0'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 1
      - name: 'Target Cache'
        uses: 'actions/cache@v3'
        env:
          cache-name: 'target-cache'
        with:
          path: 'target'
          key: "${{ matrix.toolchain-version }}-${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}"
      - name: 'Install Toolchain'
        uses: 'dtolnay/rust-toolchain@v1'
        with:
          toolchain: '${{ matrix.toolchain-version }}'
      - name: 'Run Default Feature Tests'
        run: |
          cargo test
      - name: 'Run Cloudwatch Feature Test'
        run: |
          cargo test \
            --no-default-features \
            --features=cloudwatch
      - name: 'Run S3 Feature Test'
        run: |
          cargo test \
            --no-default-features \
            --features=s3
  mandoc:
    name: 'Lint Man Page'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 1
      - name: 'Install mandoc'
        run: |
          sudo apt install mandoc
      - name: 'Lint man page'
        run: |
          make manlint
